# name: Deploy to AWS S3

# on:
#   push:
#     branches: [ master ]
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
      
#       - name: Setup Node.js environment
#         uses: actions/setup-node@v2.1.2
#         with:
#             node-version: 14.x

#       - name: Installs required tools & dependencies
#         run: |
#           sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
#           npm install

#       - name: Generates new quote
#         run: |
#           npm run prod