name: Upload quote

on:
  schedule:
    - cron: "0 */3 * * *" # every 3 hours
  workflow_dispatch:

jobs:
  quote_upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install
      - name: Run script
        run: node ./upload_quote